#!/bin/bash -x

export GO111MODULE=on 
export GOPROXY=https://goproxy.cn
# build webhook
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o namespace-service-ca-crt
# build docker image
docker build --no-cache -t daocloud.io/daocloud/namespace-service-ca-crt:latest .
rm -rf namespace-service-ca-crt

docker push daocloud.io/daocloud/namespace-service-ca-crt:latest
