apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  namespace: jiexun-test
  annotations:
    jiexun-test: "jiexun"
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
      ports:
        - containerPort: 80
          name: http
